version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable:
    - depguard
  exclusions:
    paths:
      - pkg/serve/static
      - pkg/serve/frontend/node_modules
