package push

import (
	"crypto/hkdf"
	"crypto/hmac"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

var updateVectors = flag.Bool("update-vectors", false, "rewrite relay/test/vectors.json")

const vectorsPath = "../../relay/test/vectors.json"

// sealRelayBlob is the relay's sealing (relay/src), reimplemented here only to
// pin the shared vectors and to fake a relay in tests.
func sealRelayBlob(krelay []byte, info, label string, payload map[string]any, nonce []byte) string {
	key, err := hkdf.Key(sha256.New, krelay, nil, info, 32)
	if err != nil {
		panic(err)
	}
	gcm, err := newGCM(key)
	if err != nil {
		panic(err)
	}
	// Field order is part of the vector: t, e, k, x.
	js := `{"t":` + mustJSON(payload["t"]) + `,"e":` + mustJSON(payload["e"]) + `,"k":` + mustJSON(payload["k"]) + `,"x":` + mustJSON(payload["x"]) + `}`
	rk := []byte{1}
	out := append(append([]byte(nil), rk...), nonce...)
	out = gcm.Seal(out, nonce, []byte(js), append([]byte(label), rk...))
	return b64u.EncodeToString(out)
}

func mustJSON(v any) string {
	b, err := json.Marshal(v)
	if err != nil {
		panic(err)
	}
	return string(b)
}

func seq(start byte, n int) []byte {
	b := make([]byte, n)
	for i := range b {
		b[i] = start + byte(i)
	}
	return b
}

type vectorFile struct {
	Note   string            `json:"note"`
	Device map[string]string `json:"device"`
	Relay  map[string]string `json:"relay"`
	// Collapse maps a policy tag to its collapse id.
	Collapse map[string]string `json:"collapse"`
	Envelope struct {
		Now          int64        `json:"now"`
		ID           string       `json:"id"`
		Nonce        string       `json:"nonce"`
		Notification Notification `json:"notification"`
		Plaintext    string       `json:"plaintext"` // trimmed of its padding
		Envelope     Envelope     `json:"envelope"`
	} `json:"envelope"`
	Confirm struct {
		C string `json:"c"`
		P string `json:"p"`
	} `json:"confirm"`
	Send struct {
		Body string `json:"body"`
		Sig  string `json:"sig"`
	} `json:"send"`
	Handle struct {
		Nonce   string `json:"nonce"`
		Token   string `json:"token"`
		Env     string `json:"env"`
		Expiry  int64  `json:"x"`
		Handle  string `json:"handle"`
		Challen string `json:"challenge"`
	} `json:"sealed"`
}

func buildVectors(t *testing.T) vectorFile {
	t.Helper()
	var v vectorFile
	v.Note = "Generated by pkg/push native_test.go (go test ./pkg/push -run TestVectors -update-vectors). See relay/PROTOCOL.md. Binary values are b64u unless named hex."
	secret := seq(0x00, 32)
	keys, err := DeriveDeviceKeys(secret)
	if err != nil {
		t.Fatal(err)
	}
	v.Device = map[string]string{
		"S":      b64u.EncodeToString(secret),
		"K_enc":  hex.EncodeToString(keys.Enc),
		"K_send": hex.EncodeToString(keys.Send),
		"K_col":  hex.EncodeToString(keys.Collapse),
		"kid":    hex.EncodeToString(keys.KID),
	}
	krelay := seq(0x40, 32)
	kh, _ := hkdf.Key(sha256.New, krelay, nil, "moa-relay-handle-v1", 32)
	kr, _ := hkdf.Key(sha256.New, krelay, nil, "moa-relay-reg-v1", 32)
	v.Relay = map[string]string{"KRELAY": b64u.EncodeToString(krelay), "K_handle": hex.EncodeToString(kh), "K_reg": hex.EncodeToString(kr)}
	v.Collapse = map[string]string{}
	for _, tag := range []string{"req:sess_1", "run:sess_1", "project:/home/me/dev/moa", "event:grokbot"} {
		v.Collapse[tag] = collapseID(keys, tag)
	}

	now := time.Unix(1790000000, 0)
	n := Notification{Title: "moa necesita tu decisión", Body: "Revisar «push» <nativo> & más", SessionID: "sess_1", Tag: "req:sess_1", Kind: KindAsk, Level: LevelUrgent}
	nonce := seq(0x80, 12)
	id := b64u.EncodeToString(seq(0xa0, 16))
	plain, err := EnvelopeContenttext(keys, n, now, id)
	if err != nil {
		t.Fatal(err)
	}
	env, err := sealEnvelope(keys, n, now, id, nonce)
	if err != nil {
		t.Fatal(err)
	}
	v.Envelope.Now, v.Envelope.ID, v.Envelope.Nonce = now.Unix(), id, b64u.EncodeToString(nonce)
	v.Envelope.Notification = n
	v.Envelope.Plaintext = strings.TrimRight(string(plain), " ")
	v.Envelope.Envelope = env

	v.Handle.Nonce = b64u.EncodeToString(seq(0xc0, 12))
	v.Handle.Token = strings.Repeat("ab", 32)
	v.Handle.Env = "sandbox"
	v.Handle.Expiry = now.Unix() + 90*86400
	payload := map[string]any{"t": v.Handle.Token, "e": v.Handle.Env, "k": b64u.EncodeToString(keys.Send), "x": v.Handle.Expiry}
	v.Handle.Handle = sealRelayBlob(krelay, "moa-relay-handle-v1", "moa-handle-v1", payload, seq(0xc0, 12))
	payload["x"] = now.Unix() + 300
	v.Handle.Challen = sealRelayBlob(krelay, "moa-relay-reg-v1", "moa-reg-v1", payload, seq(0xc0, 12))

	v.Confirm.C = v.Handle.Challen
	mac := hmac.New(sha256.New, keys.Send)
	mac.Write([]byte("moa-confirm-v1\x00" + v.Confirm.C))
	v.Confirm.P = b64u.EncodeToString(mac.Sum(nil))

	body, sig, err := buildSendBody(keys, v.Handle.Handle, collapseID(keys, n.Tag), env, now)
	if err != nil {
		t.Fatal(err)
	}
	v.Send.Body, v.Send.Sig = string(body), sig
	return v
}

// TestVectors pins the byte contract shared with the relay and the iOS app.
func TestVectors(t *testing.T) {
	v := buildVectors(t)
	got, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	got = append(got, '\n')
	if *updateVectors {
		if err := os.MkdirAll(filepath.Dir(vectorsPath), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(vectorsPath, got, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	want, err := os.ReadFile(vectorsPath)
	if err != nil {
		t.Fatalf("read vectors (run with -update-vectors to create): %v", err)
	}
	if string(want) != string(got) {
		t.Fatal("relay/test/vectors.json is stale: the wire contract changed; regenerate it and update the relay and iOS sides")
	}
}

func TestDeriveDeviceKeysRFC5869EmptySalt(t *testing.T) {
	// An empty salt is HashLen zero bytes (RFC 5869 §2.2); WebCrypto and
	// CryptoKit callers pass an empty salt explicitly.
	secret := seq(0, 32)
	keys, _ := DeriveDeviceKeys(secret)
	zero, _ := hkdf.Key(sha256.New, secret, make([]byte, 32), labelEnc, 32)
	if !hmac.Equal(keys.Enc, zero) {
		t.Fatal("empty salt must equal a zero salt of hash length")
	}
	if _, err := DeriveDeviceKeys(seq(0, 31)); err == nil {
		t.Fatal("a short secret must be refused")
	}
}

func TestEnvelopeRoundTripAndFixedSize(t *testing.T) {
	keys, _ := DeriveDeviceKeys(seq(7, 32))
	now := time.Unix(1790000000, 0)
	cases := []Notification{
		{Title: "t", Body: "b", SessionID: "abc", Kind: KindDone, Level: LevelActive, Tag: "run:abc"},
		{Title: strings.Repeat("ñ", 2000), Body: strings.Repeat("\u0001", 3000), Inbox: true, Kind: KindEvent, Level: LevelPassive, Tag: "event:x"},
		{Title: "x", SessionID: "../etc/passwd", Kind: KindFailed},
	}
	var sizes []int
	for _, n := range cases {
		env, err := SealEnvelope(keys, n, now)
		if err != nil {
			t.Fatal(err)
		}
		sizes = append(sizes, len(env.C))
		p, err := OpenEnvelope(keys, env, now)
		if err != nil {
			t.Fatal(err)
		}
		if p.Kind != n.Kind || !strings.HasPrefix(n.Title, p.Title) || !strings.HasPrefix(n.Body, p.Body) {
			t.Fatalf("round trip lost content: %+v", p)
		}
	}
	for _, s := range sizes {
		if s != 2768 {
			t.Fatalf("envelope size %d, want 2768", s)
		}
	}
	// Destination comes from validated fields only.
	env, _ := SealEnvelope(keys, cases[2], now)
	p, _ := OpenEnvelope(keys, env, now)
	if p.Dest != "home" || p.Sess != "" {
		t.Fatalf("invalid session id must fall back to home: %+v", p)
	}
	env, _ = SealEnvelope(keys, cases[1], now)
	p, _ = OpenEnvelope(keys, env, now)
	if p.Dest != "inbox" || p.Level != LevelPassive {
		t.Fatalf("inbox destination lost: %+v", p)
	}
}

func TestEnvelopeRejectsTamperingWrongKeyAndExpiry(t *testing.T) {
	keys, _ := DeriveDeviceKeys(seq(7, 32))
	other, _ := DeriveDeviceKeys(seq(8, 32))
	now := time.Unix(1790000000, 0)
	env, err := SealEnvelope(keys, Notification{Title: "t", Kind: KindAsk, Level: LevelUrgent}, now)
	if err != nil {
		t.Fatal(err)
	}
	raw, _ := b64u.DecodeString(env.C)
	for _, i := range []int{0, 11, 12, 500, len(raw) - 1} {
		bad := append([]byte(nil), raw...)
		bad[i] ^= 1
		if _, err := OpenEnvelope(keys, Envelope{V: 1, KID: env.KID, C: b64u.EncodeToString(bad)}, now); err == nil {
			t.Fatalf("flipping byte %d must fail", i)
		}
	}
	if _, err := OpenEnvelope(other, env, now); err == nil {
		t.Fatal("another device's key must fail")
	}
	// Same key, but the kid inside the AAD differs: authenticates nothing.
	wrongKID := env
	wrongKID.KID = b64u.EncodeToString(other.KID)
	if _, err := OpenEnvelope(keys, wrongKID, now); err == nil {
		t.Fatal("a wrong kid must fail")
	}
	if _, err := OpenEnvelope(keys, Envelope{V: 2, KID: env.KID, C: env.C}, now); err == nil {
		t.Fatal("unknown version must fail")
	}
	if _, err := OpenEnvelope(keys, Envelope{V: 1, KID: env.KID, C: env.C[:100]}, now); err == nil {
		t.Fatal("wrong size must fail")
	}
	if _, err := OpenEnvelope(keys, env, now.Add(envelopeTTL+time.Second)); err == nil {
		t.Fatal("an expired envelope must fail")
	}
}

func TestCollapseIDsAreOpaqueAndPerDevice(t *testing.T) {
	a, _ := DeriveDeviceKeys(seq(1, 32))
	b, _ := DeriveDeviceKeys(seq(2, 32))
	if again, _ := DeriveDeviceKeys(seq(1, 32)); collapseID(a, "project:/x") != collapseID(again, "project:/x") {
		t.Fatal("same tag must give the same id")
	}
	if collapseID(a, "project:/x") == collapseID(b, "project:/x") {
		t.Fatal("two devices must not share ids")
	}
	if collapseID(a, "req:s") == collapseID(a, "run:s") {
		t.Fatal("scope is part of the id")
	}
	// "a\0b" framing: no ambiguity between scope and id.
	if collapseID(a, "ab:c") == collapseID(a, "a:bc") {
		t.Fatal("scope/id boundary must matter")
	}
	if got := collapseID(a, "project:/home/me/secret"); len(got) != 22 || strings.Contains(got, "secret") {
		t.Fatalf("collapse id %q", got)
	}
	if collapseID(a, "") != "" {
		t.Fatal("no tag, no collapse")
	}
}

func TestNormalizeRelayURL(t *testing.T) {
	ok := map[string]string{
		"https://push.letmoa.run":    "https://push.letmoa.run",
		"https://Push.LetMoa.run/":   "https://push.letmoa.run",
		"https://relay.example:8443": "https://relay.example:8443",
		"http://127.0.0.1:8787":      "http://127.0.0.1:8787",
		"http://localhost:8787":      "http://localhost:8787",
	}
	for in, want := range ok {
		got, err := NormalizeRelayURL(in)
		if err != nil || got != want {
			t.Errorf("%q: got %q, %v; want %q", in, got, err, want)
		}
	}
	for _, in := range []string{
		"http://push.letmoa.run", "https://user:pw@push.letmoa.run", "https://push.letmoa.run/v1",
		"https://push.letmoa.run?x=1", "https://push.letmoa.run#f", "ftp://push.letmoa.run", "", "push.letmoa.run",
		"http://10.0.0.1:8787", "https://push.letmoa.run?",
	} {
		if _, err := NormalizeRelayURL(in); err == nil {
			t.Errorf("%q must be refused", in)
		}
	}
}
